
GET http://localhost:5000/notes
//Access Token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWxleCIsImlhdCI6MTY5MDUyOTY3NiwiZXhwIjoxNjkwNTI5NzE2fQ.b3bTIPXHMdGDVbrGy58Uw05dF6kAJrmcIEF1A_nPmaY

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWxleCIsImlhdCI6MTY5MDUyOTYyNH0.T6aEdPoXYDAsTWlGWWjRFr4d-Wpf4qDjHFXomCP7gX8"
}

### 
POST http://localhost:4000/token 
Content-Type: application/json

//Refresh Token
{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWxleCIsImlhdCI6MTY5MDUyOTYyNH0.T6aEdPoXYDAsTWlGWWjRFr4d-Wpf4qDjHFXomCP7gX8"
}

###
POST http://localhost:4000/login
Content-Type: application/json

{
    "username":"Melisa"
}