
GET http://localhost:5000/notes
//Access Token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUm9iZXJ0IiwiaWF0IjoxNjkwNDM5NjExLCJleHAiOjE2OTA0Mzk2NTF9.tGlz2Q5NEyz5Pk4Iflhdhn2aVhQzZ37PoEdAzOBU1K4
 
###
DELETE http://localhost:4000/logout
Content-Type: application/json
{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUm9iZXJ0IiwiaWF0IjoxNjkwNDM1ODU5fQ.yPM4eOsG3kj4tqJxIt-yhfnC-TaseiH0vVOt1VfbLfI"
}

### 
POST http://localhost:4000/token 
Content-Type: application/json

//Refresh Token
{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUm9iZXJ0IiwiaWF0IjoxNjkwNDM1ODU5fQ.yPM4eOsG3kj4tqJxIt-yhfnC-TaseiH0vVOt1VfbLfI"
}

###
POST http://localhost:4000/login
Content-Type: application/json

{
    "username":"Robert"
}